# Generated by Django 5.0.7 on 2024-08-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gittoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
