# Generated by Django 5.0.7 on 2024-08-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_gittoken_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gittoken',
            old_name='active',
            new_name='is_active',
        ),
    ]
