# Generated by Django 5.0.7 on 2024-08-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_active_gittoken_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gittoken',
            name='label',
            field=models.CharField(default='Demo', max_length=255),
            preserve_default=False,
        ),
    ]
