# Generated by Django 5.0.7 on 2024-08-06 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_gittoken_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('git_id', models.BigIntegerField(unique=True)),
                ('avatar_url', models.URLField()),
                ('html_url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='url',
            new_name='html_url',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='last_fetched',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='token',
        ),
        migrations.AddField(
            model_name='repository',
            name='default_branch',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='full_name',
            field=models.TextField(default='demo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='git_id',
            field=models.BigIntegerField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.author'),
        ),
    ]
