# Generated by Django 5.0.7 on 2024-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_commit_options_alter_gittoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitfile',
            name='patch',
            field=models.TextField(blank=True, null=True),
        ),
    ]
