# Generated by Django 5.0.7 on 2024-08-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_commitfile_patch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.author'),
        ),
    ]
