# Generated by Django 5.0.7 on 2024-08-27 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_commit_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ['-commited_at'], 'verbose_name_plural': 'Commits'},
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('infrequent_commits', 'Infrequent Commits'), ('mass_commits', 'Mass Commits at Odd Times'), ('plagiarism', 'Potential Plagiarism')], max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.author')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.repository')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.anomaly')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
