# Generated by Django 5.0.7 on 2024-08-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_commit_options_anomaly_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomaly',
            old_name='details',
            new_name='description',
        ),
    ]
