# Generated by Django 5.0.7 on 2024-09-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_anomaly_options_repository_webhook_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('git_id', 'owner')},
        ),
        migrations.RemoveField(
            model_name='repository',
            name='token',
        ),
    ]
